version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: bull
    versions:
    - 3.20.0
    - 3.20.1
    - 3.21.0
    - 3.21.1
    - 3.22.0
    - 3.22.1
    - 3.22.3
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: sequelize
    versions:
    - 6.5.0
    - 6.5.1
    - 6.6.1
  - dependency-name: grunt
    versions:
    - 1.3.0
  - dependency-name: sails
    versions:
    - 1.4.0
  - dependency-name: validator
    versions:
    - 13.5.2
