# This file starts MySQL and redis, to use as development
# Run with docker-compose -f docker-compose-dev.yml up
version: "3.7"

services:
  cache:
    image: redis
    ports:
      - 6379:6379
  db:
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_USER: csmm
      MYSQL_PASSWORD: mysecretpasswordissosecure
      MYSQL_DATABASE: csmm
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
  # This one is used to run the tests
  db-test:
    image: mariadb
    ports:
      - 3307:3306
    environment:
      MYSQL_USER: csmm
      MYSQL_PASSWORD: mysecretpasswordissosecure
      MYSQL_DATABASE: csmm
      MYSQL_RANDOM_ROOT_PASSWORD: "true"

volumes:
  mysql:
